package com.example.zye37.capstone;

/**
 * Created by zye37 on 4/9/2017.
 */


// PatientUser

// 1 Patient user --> Multiple exercises records; 1--> N
// Patients Thomas has exercises records for Standing Lumbar Flexion exercises and other
// exercises records on each timeStamp

// 1 Patient User --> Multiple Exercises; 1--> N
// Patients Thomas has multiple exercises choices: Standing Lumbar Flexion and etc;


public class PatientUser {
    public static final String PATIENT_KEY = "patientKey"; // for Firebase path


    private String patientKey; // each record entry has its own key
    // generated by FireBase

    // Personal Profile & Login Information
    private String userName;
    private String emailAddress;
    private String DOB;
    private String passWord;
    private String cause;
    private String programStart;

// Related Exercises Activities

    private String exerciseKey;
    private String exerciseName;
    private String exerciseTime; // TimeStamp start exercising time, Date.toString()
    private double ROM;


    // Used by FireBase for deserializing JSON
    public PatientUser() {

    }

// Used when creating from scratch

    public PatientUser(String userName, String emailAddress, String DOB, String passWord, String cause, String programStart,
                       String exerciseKey, String exerciseName, String exerciseTime, double ROM) {

        //Personal Profile & Login Information
        this.userName = userName;
        this.emailAddress = emailAddress;
        this.DOB = DOB;
        this.passWord = passWord;
        this.cause = cause;
        this.programStart = programStart;

        //Related Exercises Activities
        this.exerciseKey = exerciseKey;
        this.exerciseName = exerciseName;
        this.exerciseTime = exerciseTime;
        this.ROM = ROM;
    }
}
